apiVersion: v1
kind: Pod
spec:
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: golang
      image: golang:alpine3.12
      command: ["tail", "-f", "/dev/null"]  # this or any command that is bascially a noop is required, this is so that you don't overwrite the entrypoint of the base container
      imagePullPolicy: Always # use cache or pull image for agent
      volumeMounts:
      - name: jenkins
        mountPath: /var/jenkins
      resources:  # limits the resources your build contaienr
        requests:
          memory: "300Mi"
          cpu: "1"
        limits:
          memory: "300Mi"
          cpu: "1"
    - image: node:lts-alpine3.10
      name : node
      imagePullPolicy: Always
      volumeMounts:
        - name: jenkins
          mountPath: /var/jenkins
    - name: docker
      image: docker:18.06.1
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock # We use the k8s host docker engine
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
    - name: jenkins
      emptyDir: {}
