apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiber-deploy
  namespace: jenkins
spec:
  selector: 
    matchLabels:
      name: fiber
  template:
    metadata:
      labels:
        name: fiber
    spec:
      containers:
      - name: fiber
        image: ${image_name}:${BUILD_ID}
        ports:
        - name: http 
          containerPort: 3000
        volumeMounts:
        - name: fiber-conf
          mountPath: /config
      volumes:
      - name: fiber-conf
        configMap:
          name: fiber-conf
