apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiber-deploy
  namespace: jenkins
spec:
  selector: 
    matchLabels:
      name: fiber
  template:
    metadata:
      labels:
        name: fiber
    spec:
      containers:
      - name: fiber
        image: ${image_name}:latest
        ports:
        - name: http 
          containerPort: 3000
        volumeMounts:
        - name: fiber-conf
          mountPath: /app/.env
          subPath: .env
      volumes:
      - name: fiber-conf
        configMap:
          name: fiber-conf
---
apiVersion: v1
kind: Service
metadata:
  name: fiber-service
spec:
  selector:
    name: fiber
  ports:
    - name: fiber
      targetPort: 3000
      protocol: "TCP"
      port: 3000
  type: ClusterIP
