apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiber-deploy
  namespace: jenkins
spec:
  selector: 
    matchLabels:
      name: fiber
  template:
    metadata:
      labels:
        name: fiber
    spec:
      volumes:
      - name: fiber-conf
        configMap:
          name: fiber-conf
      containers:
      - name: fiber
        image: nginx:latest
        ports:
        - name: http 
          containerPort: 3000
        volumeMounts:
        - name: fiber-conf
          mountPath: .env
